### ISSUE TITLE
[Request] webhook-cabundle-injector controller

### ISSUE THREAD

**Issue by s1061123** [openshift/service-ca-operator#63]
In case of install K8s admission controller, ValidatingWebhookConfiguration requires CABundle as following, hence having configmap injector (as configmap-cabundle-injector controller) helps to install k8s admission controller. 

```
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: multus.openshift.io
webhooks:
  - name: net-attach-def-admission-controller-isolating-config.k8s.io
    clientConfig:
      service:
        name: net-attach-def-admission-controller-service
        namespace: openshift-multus-admission-controller
        path: "/isolate"
      caBundle: {{.CABundle}}  /// HERE!
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
```
